# This is a simple workflow to get information about the windows runner build environment for GitHub Actions

name: Get Ubuntu Environment

# Controls when the action will run. 
on:
  # Run this workflow after a push
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show some installed tool versions
        run: |
          cpp --version
          cpp -dM
        shell: bash